### ISSUE TITLE
Can't get to work

### ISSUE THREAD

**Issue by InanimateCrbnRod** [BenNatNB/VGMGUI#3]
Hey I'm trying to use this program but no matter which version of vgmstream I use with it it always gives an error when trying to open any minipsf from FF7, even though the files open just fine when I don't use the gui version. I would prefer to use the gui as I'm completely in over my head without a gui lol. All I'm trying to do is strip channels from PSF files. I'd like to seperate all 24 audo channels from a psf into seperate wav files. been trying to find a way to do this on windows for awhile. Thank you in advance for any help you might be able to offer me.

**Comment by BENICHN** [comment]
Hi, thank you for having reported this issue.
The fact that VGMGUI gives you an error whereas the cli succeeds in opening the file would be pretty strange, can you give me these psf files ? I have downloaded some [here](http://psf.joshw.info/f/Final%20Fantasy%20VII%20(1997-01-31)(Square)%5bPS1%5d.7z) and personnaly I can't open these files with the cli. When you say 'when I don't use the gui version', are you talking about the cli or the foobar2000 plugin ?
