### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Benn3557** [BenNatNB/VGMGUI#4]
hey! it's a question not a issues... My question, how do you make the files readable? i wanna modify S&SASR Wii and there are (.was) files, how i can play the sound file and how i can replace it to a new music?

**Comment by BENICHN** [comment]
Hello, if I understand your question, you want to modify an audio file but keeping it readable to the console. This impossible with vgmstream and thus with VGMGUI because vgmstream in a decoder. To encode audio you have to use a program specific to this format which you'll find on internet

**Comment by Benn3557** [comment]
Rip for me. :( there is no program/tool to replace the sound file, i have to working with hxd :P
